namespace TypedIcons.Generator;

internal static class CodeTemplates
{
    public const string IconDataClass =
        """
        /// <auto-generated />
        namespace TypedIcons;

        public readonly partial record struct IconData(
            string SvgContent, 
            string ViewBox, 
            string Width, 
            string Height
        );
        """;

    public const string IconComponent =
        """
        /// <auto-generated />
        using Microsoft.AspNetCore.Components;
        using Microsoft.AspNetCore.Components.Rendering;
        
        namespace TypedIcons;
        
        public partial class Icon : ComponentBase
        {
            [Parameter] public IconData? Value { get; set; }
            
            [Parameter] public string? Size { get; set; }
            
            [Parameter] public string? Width { get; set; }
            
            [Parameter] public string? Height { get; set; }
        
            protected override void BuildRenderTree(RenderTreeBuilder builder)
            {
                if (Value is null) 
                    return;
                
                var iconData = Value.Value;
                var (width, height) = CalculateDimensions(iconData);
                
                builder.OpenElement(0, "svg");
                builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
                builder.AddAttribute(2, "viewBox", iconData.ViewBox);
                builder.AddAttribute(3, "width", width);
                builder.AddAttribute(4, "height", height);
                builder.AddAttribute(5, "fill", "currentColor");
        
                builder.AddMarkupContent(6, iconData.SvgContent);
        
                builder.CloseElement();
            }
        
            private (string, string) CalculateDimensions(IconData iconData)
            {
                string width, height;
                
                if (Size is not null)
                {
                    width = height = Size;
                }
                else if (Width is not null && Height is not null)
                {
                    width = Width;
                    height = Height;
                }
                else if (Width is not null)
                {
                    width = height = Width;
                }
                else if (Height is not null)
                {
                    width = height = Height;
                }
                else
                {
                    width = height = iconData.Width;
                }
                
                return (width, height);
            }
        }
        """;
    
    public const string EmptyIconsClass =
        """
        /// <auto-generated />
        namespace TypedIcons;

        public static partial class Icons {}
        """;
}