namespace TypedIcons.Generator;

internal static class CodeTemplates
{
    public const string IconDataClass =
        """
        /// <auto-generated />
        namespace TypedIcons;

        public readonly partial record struct IconData(
            string SvgContent, 
            string ViewBox, 
            string Width, 
            string Height
        );
        """;
    
    public const string EmptyIconsClass =
        """
        /// <auto-generated />
        namespace TypedIcons;

        public static partial class Icons {}
        """;
}