using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace TypedIcons.Generator;

[Generator]
public class IconGenerator : IIncrementalGenerator
{
    private const string IconDataTemplate =
        """
        /// <auto-generated />
        namespace TypedIcons;
        
        public readonly partial record struct IconData(
            string SvgContent, 
            string ViewBox, 
            string Width, 
            string Height
        );
        """;

    private const string EmptyIconsClassTemplate =
        """
        /// <auto-generated />
        namespace TypedIcons;
        
        public static partial class Icons {}
        """;
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("IconData.g.cs", SourceText.From(IconDataTemplate, Encoding.UTF8)));
        
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("Icons.g.cs", SourceText.From(EmptyIconsClassTemplate, Encoding.UTF8)));
    }
}